/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
/* tslint:disable */

import '@stencil/core';




declare global {
  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}

  namespace StencilComponents {

    interface DisplayCard {
      'cardbody': string;
      'cardtitle': string;
    }
  }


    interface HTMLDisplayCardElement extends StencilComponents.DisplayCard, HTMLStencilElement {}

    var HTMLDisplayCardElement: {
      prototype: HTMLDisplayCardElement;
      new (): HTMLDisplayCardElement;
    };
    

  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {
    'display-card': JSXElements.DisplayCardAttributes;
    }
  }

  namespace JSXElements {

    export interface DisplayCardAttributes extends HTMLAttributes {
      'cardbody'?: string;
      'cardtitle'?: string;
    }
  }

  interface HTMLElementTagNameMap {
    'display-card': HTMLDisplayCardElement
  }

  interface ElementTagNameMap {
    'display-card': HTMLDisplayCardElement;
  }
}
declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;